const positions = {
  아트록스: { position: "top", trait: ["픽률높은", "피지컬,딜탱"] },
  아리: { position: "mid", trait: ["픽률높은", "이쁨", "생존기"] },
  아칼리: { position: "mid", trait: ["픽률높은", "이쁨", "생존기"] },
  알리스타: { position: "support", trait: ["힙스터", "뚜벅이"] },
  아크샨: { position: "mid", trait: ["피지컬", "생존기"] },
  아무무: { position: "jungle, support", trait: ["힙스터", "뇌지컬"] },
  애니비아: { position: "mid", trait: ["뇌지컬", "후반"] },
  애니: { position: "mid, support", trait: ["뚜벅이", "힙스터"] },
  아펠리오스: {
    position: "adc",
    trait: ["픽률높은", "후반", "뚜벅이", "피지컬"],
  },
  애쉬: { position: "adc", trait: ["픽률높은", "뚜벅이", "이쁨"] },
  아우렐리온솔: { position: "mid", trait: ["힙스터", "뇌지컬", "후반"] },
  오로라: { position: "top, mid", trait: ["뇌지컬", "생존기"] },
  아지르: { position: "mid", trait: ["후반", "힙스터"] },
  바드: { position: "support", trait: ["힙스터", "뇌지컬"] },
  벨베스: { position: "jungle", trait: ["딜탱", "피지컬"] },
  세트: { position: "top", trait: ["딜탱", "뚜벅이"] },
  제드: { position: "mid", trait: ["픽률높은", "피지컬"] },
  자야: { position: "adc", trait: ["생존기", "이쁨"] },
  제라스: { position: "mid", trait: ["뚜벅이", "후반"] },
  트위치: { position: "adc", trait: ["힙스터", "후반"] },
  카이사: { position: "adc", trait: ["픽률높은", "피지컬", "이쁨", "생존기"] },
  리신: { position: "jungle", trait: ["픽률높은", "피지컬", "딜탱"] },
  자르반4세: { position: "jungle", trait: ["픽률높은", "딜탱", "생존기"] },
  리븐: { position: "top", trait: ["픽률높은", "딜탱", "이쁨", "생존기"] },
  모르가나: { position: "support", trait: ["뇌지컬", "이쁨"] },
  킨드레드: { position: "jungle", trait: ["후반", "피지컬", "생존기"] },
  렉사이: { position: "jungle", trait: ["힙스터", "뚜벅이", "딜탱"] },
  소라카: { position: "support", trait: ["힙스터", "뇌지컬"] },
  카서스: { position: "mid,jungle", trait: ["후반", "힙스터", "뚜벅이"] },
  잔나: { position: "support", trait: ["뇌지컬", "후반", "이쁨"] },
  알리: { position: "support", trait: ["힙스터", "후반"] },
  바루스: { position: "adc, top", trait: ["뚜벅이"] },
  베이가: { position: "mid", trait: ["후반", "뇌지컬", "뚜벅이"] },
  신지드: { position: "top", trait: ["힙스터", "후반"] },
  사일러스: { position: "mid", trait: ["픽률높은", "피지컬", "생존기"] },
  다리우스: { position: "top", trait: ["피지컬", "뚜벅이", "딜탱"] },
  이렐리아: { position: "top", trait: ["피지컬", "딜탱", "이쁨"] },
  피오라: { position: "top", trait: ["피지컬", "딜탱", "이쁨"] },
  케넨: { position: "top", trait: ["뇌지컬", "후반"] },
  제이스: { position: "top", trait: ["뚜벅이", "피지컬"] },
  탐켄치: { position: "support", trait: ["힙스터"] },
  리산드라: { position: "mid", trait: ["뇌지컬", "생존기"] },
  시비르: { position: "adc", trait: ["후반", "힙스터", "이쁨"] },
  세주아니: { position: "jungle", trait: ["뇌지컬", "생존기"] },
  노틸러스: { position: "support", trait: ["픽률높은", "피지컬"] },
  블리츠크랭크: { position: "support", trait: ["피지컬"] },
  클레드: { position: "top", trait: ["힙스터", "딜탱"] },
  갱플랭크: { position: "top", trait: ["딜탱", "피지컬"] },
  파이크: { position: "support", trait: ["피지컬", "힙스터", "생존기"] },
  모데카이저: { position: "top", trait: ["딜탱", "뚜벅이"] },
  카밀: { position: "top", trait: ["픽률높은", "피지컬"] },
  드레이븐: { position: "adc", trait: ["뚜벅이", "피지컬"] },
  잭스: { position: "top", trait: ["픽률높은", "피지컬"] },
  세라핀: { position: "mid, support", trait: ["힙스터", "뚜벅이", "이쁨"] },
  피즈: { position: "mid", trait: ["피지컬", "생존기"] },
  케인: { position: "jungle", trait: ["생존기", "피지컬"] },
  오리아나: { position: "mid", trait: ["픽률높은", "후반", "뚜벅이"] },
  아이번: { position: "jungle", trait: ["힙스터", "후반", "뇌지컬"] },
  카타리나: { position: "mid", trait: ["피지컬", "생존기", "이쁨"] },
  엘리스: { position: "jungle", trait: ["피지컬"] },
  뽀삐: { position: "top", trait: ["힙스터"] },
  시빌: { position: "adc", trait: ["피지컬", "후반"] },
  진: { position: "adc", trait: ["픽률높은", "뚜벅이"] },
  스웨인: { position: "mid", trait: ["힙스터", "뚜벅이"] },
  카사딘: { position: "mid", trait: ["후반", "뇌지컬"] },
  코르키: { position: "mid", trait: ["후반", "힙스터"] },
  다이애나: { position: "jungle", trait: ["피지컬", "후반"] },
  나서스: { position: "top", trait: ["후반", "뇌지컬"] },
  우르곳: { position: "top", trait: ["피지컬", "딜탱"] },
  미스포츈: { position: "adc", trait: ["뚜벅이", "뇌지컬", "이쁨"] },
  레오나: { position: "support", trait: ["픽률높은", "후반"] },
  스카너: { position: "jungle", trait: ["후반", "뇌지컬"] },
  나미: { position: "support", trait: ["픽률높은", "뚜벅이"] },
  야스오: { position: "mid", trait: ["픽률높은", "피지컬"] },
  티모: { position: "top", trait: ["힙스터", "뚜벅이", "뇌지컬"] },
  에코: { position: "jungle", trait: ["피지컬", "후반", "생존기"] },
  그라가스: { position: "top, jungle", trait: ["후반", "생존기", "뇌지컬"] },
  케일: { position: "top", trait: ["후반", "힙스터"] },
  코그모: { position: "adc", trait: ["후반", "힙스터", "뚜벅이"] },
  그레이브즈: { position: "jungle", trait: ["픽률높은", "피지컬", "생존기"] },
  나르: { position: "top", trait: ["피지컬", "딜탱", "생존기"] },
  사이온: { position: "top", trait: ["후반", "뇌지컬"] },
  레넥톤: { position: "top", trait: ["픽률높은", "딜탱", "생존기"] },
  조이: { position: "mid", trait: ["뇌지컬", "힙스터"] },
  람머스: { position: "jungle", trait: ["후반", "힙스터", "뇌지컬"] },
  자이라: { position: "support, jungle", trait: ["힙스터", "뚜벅이"] },
  질리언: { position: "mid, support", trait: ["뇌지컬", "후반"] },
  직스: { position: "adc, mid", trait: ["힙스터", "뇌지컬"] },
  제리: { position: "adc, mid", trait: ["피지컬", "후반", "생존기"] },
  자크: { position: "jungle", trait: ["힙스터", "뇌지컬", "생존기"] },
  유미: { position: "support", trait: ["힙스터", "후반"] },
  요릭: { position: "top", trait: ["뚜벅이", "피지컬", "딜탱"] },
  요네: { position: "top, mid", trait: ["픽률높은", "피지컬", "생존기"] },
  신짜오: { position: "jungle", trait: ["피지컬", "뚜벅이", "딜탱"] },
  워윅: { position: "jungle, top", trait: ["힙스터", "딜탱", "뚜벅이"] },
  볼리베어: { position: "top, jungle", trait: ["뚜벅이", "딜탱"] },
  블라디미르: { position: "top", trait: ["후반", "뇌지컬", "생존기"] },
  빅토르: { position: "mid", trait: ["뇌지컬", "후반", "뚜벅이"] },
  비에고: { position: "jungle, mid", trait: ["픽률높은", "피지컬", "딜탱"] },
  바이: { position: "jungle", trait: ["피지컬", "딜탱"] },
  벡스: { position: "mid", trait: ["뇌지컬", "후반"] },
  벨코즈: { position: "mid, support", trait: ["힙스터", "후반", "뚜벅이"] },
  베인: { position: "adc, top", trait: ["피지컬", "후반"] },
  우디르: { position: "top", trait: ["힙스터", "뚜벅이"] },
  트위스티드페이트: { position: "mid", trait: ["뇌지컬", "후반"] },
  트린다미어: { position: "top", trait: ["피지컬", "생존기"] },
  트런들: { position: "top, jungle", trait: ["힙스터", "딜탱", "뚜벅이"] },
  트리스티나: { position: "adc, mid", trait: ["힙스터", "후반", "생존기"] },
  쓰레쉬: { position: "support", trait: ["픽률높은", "후반", "생존기"] },
  타릭: { position: "support", trait: ["힙스터", "뚜벅이"] },
  탈론: { position: "mid, jungle", trait: ["피지컬", "생존기"] },
  탈리야: { position: "mid, jungle", trait: ["힙스터", "후반"] },
  신드라: { position: "mid", trait: ["픽률높은", "뚜벅이", "이쁨"] },
  소나: { position: "support", trait: ["힙스터", "뚜벅이", "이쁨"] },
  스몰더: { position: "mid, adc", trait: ["힙스터", "피지컬", "후반"] },
  쉬바나: { position: "jungle", trait: ["뚜벅이", "딜탱"] },
  쉔: { position: "top, support", trait: ["후반", "뇌지컬", "딜탱"] },
  샤코: { position: "jungle, support", trait: ["힙스터", "뇌지컬", "생존기"] },

  세나: { position: "adc, support", trait: ["픽률높은", "뇌지컬"] },
  사미라: { position: "adc", trait: ["피지컬"] },
  라이즈: { position: "mid, top", trait: ["뇌지컬", "후반"] },
  럼블: { position: "top, jungle", trait: ["힙스터", "피지컬", "뚜벅이"] },
  렝가: { position: "top, jungle", trait: ["피지컬", "힙스터"] },
  레나타글라스크: { position: "support", trait: ["힙스터", "후반"] },
  렐: { position: "support", trait: ["픽률높은", "피지컬"] },
  라칸: { position: "support", trait: ["힙스터", "후반"] },
  퀸: { position: "top", trait: ["힙스터", "피지컬", "생존기"] },
  키아나: { position: "top, jungle", trait: ["피지컬", "생존기"] },
  판테온: { position: "mid, top", trait: ["딜탱", "뚜벅이"] },
  오른: { position: "top", trait: ["후반", "뇌지컬"] },
  올라프: { position: "top, jungle", trait: ["힙스터", "뚜벅이", "딜탱"] },
  누누와윌럼프: { position: "jungle", trait: ["후반", "뇌지컬"] },
  녹턴: { position: "jungle", trait: ["픽률높은", "딜탱", "뚜벅이"] },
  닐라: { position: "adc", trait: ["힙스터", "생존기"] },
  니달리: { position: "jungle", trait: ["피지컬", "생존기"] },
  니코: { position: "mid", trait: ["힙스터", "후반"] },
  나피리: { position: "mid", trait: ["힙스터", "후반"] },
  오공: { position: "top, jungle", trait: ["힙스터", "딜탱"] },
  밀리오: { position: "support", trait: ["힙스터", "후반", "뇌지컬"] },
  마스터이: { position: "jungle", trait: ["피지컬", "후반"] },
  마오카이: { position: "support, jungle", trait: ["후반", "뇌지컬"] },
  말자하: { position: "mid", trait: ["뇌지컬", "후반", "뚜벅이"] },
  말파이트: { position: "top", trait: ["후반", "뇌지컬", "뚜벅이"] },
  럭스: { position: "support, mid", trait: ["뇌지컬", "뚜벅이", "이쁨"] },
  룰루: { position: "support", trait: ["픽률높은", "후반"] },
  루시안: { position: "support, mid", trait: ["픽률높은", "후반", "생존기"] },
  릴리아: { position: "jungle", trait: ["후반", "피지컬"] },
  르블랑: { position: "mid", trait: ["픽률높은", "생존기", "이쁨"] },
  크산테: { position: "top", trait: ["픽률높은", "생존기"] },
  카직스: { position: "jungle", trait: ["픽률높은", "피지컬"] },
  카르마: { position: "support, mid", trait: ["픽률높은", "뇌지컬"] },
  칼리스타: { position: "adc", trait: ["피지컬"] },
  징크스: { position: "adc", trait: ["픽률높은", "후반", "뚜벅이"] },
  일라오이: { position: "top", trait: ["뚜벅이", "딜탱"] },
  흐웨이: { position: "mid", trait: ["픽률높은", "후반"] },
  하이머딩거: { position: "top", trait: ["힙스터", "뇌지컬", "뚜벅이"] },
  헤카림: { position: "jungle", trait: ["피지컬", "딜탱", "생존기"] },
  그웬: { position: "top", trait: ["피지컬", "이쁨", "딜탱"] },
  가렌: { position: "top", trait: ["뚜벅이", "딜탱"] },
  갈리오: { position: "mid", trait: ["뇌지컬"] },
  피들스틱: { position: "jungle", trait: ["뇌지컬", "후반"] },
  이즈리얼: { position: "adc", trait: ["픽률높은", "생존기"] },
  이블린: { position: "jungle", trait: ["뇌지컬", "이쁨"] },
  문도박사: { position: "top, jungle", trait: ["후반", "뚜벅이"] },
  초가스: { position: "top", trait: ["힙스터", "후반", "뚜벅이"] },
  카시오페아: { position: "top, mid", trait: ["피지컬", "뚜벅이"] },
  케이틀린: { position: "adc", trait: ["픽률높은", "뚜벅이"] },
  브라이어: { position: "jungle", trait: ["피지컬"] },
  브라움: { position: "support", trait: ["픽률높은"] },
  브랜드: { position: "jungle, mid", trait: ["뚜벅이"] },
};

export default positions;
